[package]
name = "roadwits-proto"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
tonic = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
tonic-health = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
